# Generated by Django 4.2.5 on 2024-04-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0004_alter_customuser_cooking_skill_lvl'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_img',
            field=models.FileField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
