# Generated by Django 4.2.5 on 2023-11-05 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_title_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cooking_instructions',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title_img',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/'),
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('step_img', models.ImageField(blank=True, null=True, upload_to='recipe_images/steps')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
    ]
