# Generated by Django 4.2.5 on 2024-03-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_ingredients_recipe_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='id',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
