# Generated by Django 4.2.5 on 2024-05-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_recipe_ingredients_remove_recipe_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', to='recipes.recipeingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.ManyToManyField(related_name='recipes', to='recipes.recipestep'),
        ),
    ]
