# Generated by Django 4.2.5 on 2024-06-11

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_ingredients_recipe_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
