# Generated by Django 4.2.5 on 2024-06-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_ingredient_id_alter_ingredient_ingredient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
